# Generated by Django 4.2 on 2023-04-17 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='meta_category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.metacategory'),
            preserve_default=False,
        ),
    ]
